
start <- exp space !.
space <- [ \t]*
op <- space < [-+] > { push_string(yytext); }

exp <- &{ start() } value (op value)* { stop("exp"); flatten_last() } / &{ reject() }

value <- space (number / word)
number <- < [0-9]+ > { push_simple("number", yytext); }
word <- < [a-zA-Z_] [a-zA-Z_0-9]* > { push_simple("word", yytext); }


# multi-match style
# number <- space &{ start() } < [0-9]+ > { push_string(yytext), stop("number"); } / &{ reject() }

